---
title: Maine Climate Protectors Petition
timezone: America/New_York
collections:
  gallery:
    title: Gallery
    output: true
    uploads:
    - file: "/uploads/20171030_090303.jpg"
      name: Some waves on Monhegan
      date: 2017-12-20 05:00:00.000000000 Z
    - file: "/uploads/2d4bee9317294f87e54c5f855be5f138--humboldt-county-dairy.jpg"
      name: A goat I found online.
      date: 2017-12-19 05:00:00.000000000 Z
    - file: "/uploads/Jan%2024%20Flyer-FINAL.docx"
      name: Print Flyer for Jan 24
      date: 2018-01-15 05:00:00.000000000 Z
    - file: "/uploads/MCP%20painted%20banner.jpg"
      name: The painted Maine Climate Protectors banner
      date: 2018-01-16 05:00:00.000000000 Z
    - file: "/uploads/mediaadvisory_petitiondrop_1_22.pdf"
      name: Media Advisory for Jan 24th
      date: 2018-01-22 05:00:00.000000000 Z
    - file: "/uploads/ME.FB.EventPhoto.png"
      name: AART Youth Gets Ready
      date: 2018-01-23 05:00:00.000000000 Z
    - file: "/uploads/Petition%201-23-18%20Final%20wAppendix.zip"
      name: The Petition (final, zip with appendices)
      date: 2018-01-24 05:00:00.000000000 Z
    - file: "/uploads/Petition%201-23-18%20FINAL.pdf"
      name: The Petition (final, pdf)
      date: 2018-01-24 05:00:00.000000000 Z
    - file: "/uploads/IMG_0964-fd18b2.jpg"
      name: The petition is handed off to the DEP
      date: 2018-01-24 21:00:00.000000000 Z
    - file: "/uploads/2018-01-24%2014.37.26.jpg"
      name: The first speaker
      date: 2018-01-25 05:00:00.000000000 Z
    - file: "/uploads/2018-01-24%2014.32.24.jpg"
      name: The gathered crowd
      date: 2018-01-25 05:00:00.000000000 Z
    - file: "/uploads/Climate%20Change%20II%20-%20Phelps%20Turner.jpg"
      name: Speaker at the celebration
      date: 2018-01-25 05:00:00.000000000 Z
    - file: "/uploads/2018-01-24%2014.35.58.jpg"
      name: The MCs at the celebration
      date: 2018-01-24 05:00:00.000000000 Z
    - file: "/uploads/2018-01-24%2014.36.05.jpg"
      name: The crowd at the celebration
      date: 2018-01-24 05:00:00.000000000 Z
    - file: "/uploads/2018-01-24%2014.37.26.jpg"
      name: A speaker at the celebration
      date: 2018-01-24 05:00:00.000000000 Z
    - file: "/uploads/2018-01-24%2014.43.52.jpg"
      name: A speaker at the celebration
      date: 2018-01-24 05:00:00.000000000 Z
    - file: "/uploads/2018-01-24%2014.50.43.jpg"
      name: A speaker at the celebration
      date: 2018-01-24 05:00:00.000000000 Z
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
side_bar:
  posts:
    vw_threshold: 1000
    quantity: 5
  uploads:
    vw_threshold: 1000
    quantity: 5
site_colors:
  primary_background: "#20343b"
  light_background: "#32515c"
  dark_background: "#17252a"
  primary_font: "#ffffff"
  secondary_font: "#e9f9c9"
  tertiary_font: "#f2fce0"
contact_email: maineclimateprotectors@gmail.com
