---
title: Maine Climate Protectors Petition
timezone: America/New_York
collections:
  gallery:
    title: Gallery
    output: true
    uploads:
    - file: "/uploads/20171030_090303.jpg"
      name: Some waves on Monhegan
      date: 2017-12-20 05:00:00.000000000 Z
    - file: "/uploads/2d4bee9317294f87e54c5f855be5f138--humboldt-county-dairy.jpg"
      name: A goat I found online.
      date: 2017-12-19 05:00:00.000000000 Z
    - file: "/uploads/2017MaineClimateProtectorsDEPPetition.pdf"
      name: The Petition itself (December 2017)
      date: 2017-12-27 05:00:00.000000000 Z
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
side_bar:
  posts:
    vw_threshold: 1000
    quantity: 5
  uploads:
    vw_threshold: 1000
    quantity: 5
site_colors:
  primary_background: "#20343b"
  light_background: "#32515c"
  dark_background: "#17252a"
  primary_font: "#ffffff"
  secondary_font: "#e9f9c9"
  tertiary_font: "#f2fce0"
